name: Android APK Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract Android Project
        run: |
          mkdir buildsrc
          unzip JD_Retailer_BUILD_READY.zip -d buildsrc

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK
        run: sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.10.2'

      - name: Build APK
        working-directory: buildsrc
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: JD-Retailer-APK
          path: buildsrc/app/build/outputs/apk/debug/app-debug.apk
